# Generated by Django 5.1.5 on 2025-06-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_recieve_mailaddress_userprofile_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmail',
            name='gmail_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gmailパスワード'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmailアドレス'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='mail_address_image',
            field=models.ImageField(blank=True, null=True, upload_to='chara_images/', verbose_name='メルアド画像'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='second_message',
            field=models.TextField(blank=True, null=True, verbose_name='2stメール'),
        ),
        migrations.AlterField(
            model_name='jmail',
            name='conditions_message',
            field=models.TextField(blank=True, null=True, verbose_name='アドレス内1stメール'),
        ),
    ]
