# Generated by Django 5.1.5 on 2025-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_jmail_gmail_password_jmail_mail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmail',
            name='chara_image',
            field=models.ImageField(blank=True, null=True, upload_to='chara_images/', verbose_name='キャラ画像'),
        ),
    ]
