# Generated by Django 5.1.5 on 2025-06-21 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_jmail_chara_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmail',
            name='submitted_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
