# Generated by Django 5.1.5 on 2025-08-18 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_jmail_submitted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmax',
            name='iikamo_sumitted_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='いいかも送信済みユーザー'),
        ),
    ]
