# Generated by Django 5.1.5 on 2025-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_pcmax_iikamo_sumitted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmax',
            name='confirmation_mail',
            field=models.TextField(blank=True, null=True, verbose_name='メアド送信確認メッセージ'),
        ),
    ]
