# Generated by Django 5.1.5 on 2025-08-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_pcmax_confirmation_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='happymail',
            name='confirmation_mail',
            field=models.TextField(blank=True, null=True, verbose_name='メアド送信確認メッセージ'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='gmail_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gmailパスワード'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmailアドレス'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='post_return_message',
            field=models.TextField(blank=True, null=True, verbose_name='掲示板からの返信メッセージ'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='confirmation_mail',
            field=models.TextField(blank=True, null=True, verbose_name='メアド送信確認メッセージ'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='post_return_message',
            field=models.TextField(blank=True, null=True, verbose_name='掲示板からの返信メッセージ'),
        ),
    ]
