# Generated by Django 5.1.5 on 2025-08-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_happymail_confirmation_mail_happymail_gmail_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happymail',
            name='conditions_message',
        ),
        migrations.AlterField(
            model_name='happymail',
            name='post_return_message',
            field=models.TextField(blank=True, null=True, verbose_name='掲示板からの返信に対するメッセージ'),
        ),
        migrations.AlterField(
            model_name='jmail',
            name='post_return_message',
            field=models.TextField(blank=True, null=True, verbose_name='掲示板からの返信に対するメッセージ'),
        ),
    ]
