# Generated by Django 5.1.5 on 2025-09-08 07:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_happymail_conditions_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmail',
            name='young_submitted_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
