# Generated by Django 5.2.10 on 2026-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_jmail_young_submitted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='happymail',
            name='condition_message',
            field=models.TextField(blank=True, null=True, verbose_name='アドレス内1stメール'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='self_promotion',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='システムプロンプト'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='システムプロンプト'),
        ),
        migrations.AddField(
            model_name='pcmax',
            name='fst_flug',
            field=models.BooleanField(default=True, verbose_name='fstフラグ'),
        ),
        migrations.AddField(
            model_name='pcmax',
            name='system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='システムプロンプト'),
        ),
        migrations.AddField(
            model_name='pcmax',
            name='two_message_flug',
            field=models.BooleanField(default=False, verbose_name='2通メール送信フラグ'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
