# Generated by Django 5.1.5 on 2025-10-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_jmail_young_submitted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='happymail',
            name='condition_message',
            field=models.TextField(blank=True, null=True, verbose_name='アドレス内1stメール'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
