# Generated by Django 5.2.10 on 2026-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_happymail_condition_message_happymail_self_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='happymail',
            name='prof_search_area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='プロフィール検索エリア'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='prof_search_height_max',
            field=models.CharField(blank=True, choices=[('150～154', '150～154'), ('155～159', '155～159'), ('160～164', '160～164'), ('165～169', '165～169'), ('ナイショ', 'ナイショ')], max_length=10, null=True, verbose_name='プロフィール検索希望身長(上)'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='prof_search_height_min',
            field=models.CharField(blank=True, choices=[('150～154', '150～154'), ('155～159', '155～159'), ('160～164', '160～164'), ('165～169', '165～169'), ('ナイショ', 'ナイショ')], max_length=10, null=True, verbose_name='プロフィール検索希望身長(下)'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='prof_search_oldest_age',
            field=models.CharField(blank=True, choices=[('ナイショ', 'ナイショ'), ('18～19歳', '18～19歳'), ('20代前半', '20代前半'), ('20代半ば', '20代半ば'), ('20代後半', '20代後半')], max_length=10, null=True, verbose_name='プロフィール検索希望年齢(上)'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='prof_search_youngest_age',
            field=models.CharField(blank=True, choices=[('ナイショ', 'ナイショ'), ('18～19歳', '18～19歳'), ('20代前半', '20代前半'), ('20代半ば', '20代半ば'), ('20代後半', '20代後半')], max_length=10, null=True, verbose_name='プロフィール検索希望年齢(下)'),
        ),
    ]
