# Generated by Django 5.2.10 on 2026-03-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_happymail_prof_search_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happymail',
            name='age',
            field=models.CharField(blank=True, choices=[('ナイショ', 'ナイショ'), ('18～19歳', '18～19歳'), ('20代前半', '20代前半'), ('20代半ば', '20代半ば'), ('20代後半', '20代後半'), ('30代前半', '30代前半'), ('30代半ば', '30代半ば'), ('30代後半', '30代後半'), ('40代前半', '40代前半'), ('40代半ば', '40代半ば'), ('40代後半', '40代後半'), ('50代前半', '50代前半'), ('50代半ば', '50代半ば'), ('50代後半', '50代後半'), ('60歳以上', '60歳以上')], max_length=6, null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='height',
            field=models.CharField(blank=True, choices=[('150～154', '150～154'), ('155～159', '155～159'), ('160～164', '160～164'), ('165～169', '165～169'), ('170～174', '170～174'), ('175～179', '175～179'), ('180～184', '180～184'), ('185～', '185～'), ('ナイショ', 'ナイショ'), ('指定しない', '指定しない')], max_length=10, null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='prof_search_height_max',
            field=models.CharField(blank=True, choices=[('150～154', '150～154'), ('155～159', '155～159'), ('160～164', '160～164'), ('165～169', '165～169'), ('170～174', '170～174'), ('175～179', '175～179'), ('180～184', '180～184'), ('185～', '185～'), ('ナイショ', 'ナイショ'), ('指定しない', '指定しない')], max_length=10, null=True, verbose_name='プロフィール検索希望身長(上)'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='prof_search_height_min',
            field=models.CharField(blank=True, choices=[('150～154', '150～154'), ('155～159', '155～159'), ('160～164', '160～164'), ('165～169', '165～169'), ('170～174', '170～174'), ('175～179', '175～179'), ('180～184', '180～184'), ('185～', '185～'), ('ナイショ', 'ナイショ'), ('指定しない', '指定しない')], max_length=10, null=True, verbose_name='プロフィール検索希望身長(下)'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='prof_search_oldest_age',
            field=models.CharField(blank=True, choices=[('ナイショ', 'ナイショ'), ('18～19歳', '18～19歳'), ('20代前半', '20代前半'), ('20代半ば', '20代半ば'), ('20代後半', '20代後半'), ('30代前半', '30代前半'), ('30代半ば', '30代半ば'), ('30代後半', '30代後半'), ('40代前半', '40代前半'), ('40代半ば', '40代半ば'), ('40代後半', '40代後半'), ('50代前半', '50代前半'), ('50代半ば', '50代半ば'), ('50代後半', '50代後半'), ('60歳以上', '60歳以上')], max_length=10, null=True, verbose_name='プロフィール検索希望年齢(上)'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='prof_search_youngest_age',
            field=models.CharField(blank=True, choices=[('ナイショ', 'ナイショ'), ('18～19歳', '18～19歳'), ('20代前半', '20代前半'), ('20代半ば', '20代半ば'), ('20代後半', '20代後半'), ('30代前半', '30代前半'), ('30代半ば', '30代半ば'), ('30代後半', '30代後半'), ('40代前半', '40代前半'), ('40代半ば', '40代半ば'), ('40代後半', '40代後半'), ('50代前半', '50代前半'), ('50代半ば', '50代半ば'), ('50代後半', '50代後半'), ('60歳以上', '60歳以上')], max_length=10, null=True, verbose_name='プロフィール検索希望年齢(下)'),
        ),
    ]
