# Generated by Django 5.2.10 on 2026-03-19 03:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_happymail_age_alter_happymail_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmail',
            name='activity_area',
            field=models.CharField(blank=True, choices=[('東京都', '東京都')], max_length=5, null=True, verbose_name='移住地'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='age',
            field=models.CharField(blank=True, choices=[('18~21', '18~21'), ('22~25', '22~25'), ('26~29', '26~29')], max_length=10, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A型', 'A型'), ('B型', 'B型'), ('O型', 'O型'), ('AB型', 'AB型')], max_length=5, null=True, verbose_name='血液型'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='body_shape',
            field=models.CharField(blank=True, choices=[('細身', '細身'), ('キモチ細身', 'キモチ細身'), ('標準', '標準'), ('ナイスバディー', 'ナイスバディー'), ('グラマー', 'グラマー')], max_length=20, null=True, verbose_name='スタイル'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='detail_activity_area',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='height',
            field=models.CharField(blank=True, choices=[('150～154cm', '150～154cm'), ('155～159cm', '155～159cm'), ('160～164cm', '160～164cm'), ('165～169cm', '165～169cm'), ('170～174cm', '170～174cm'), ('175～179cm', '175～179cm')], max_length=10, null=True, verbose_name='身長'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='job',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='職業'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='looks',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ルックス'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='personality',
            field=models.CharField(blank=True, choices=[('明るい', '明るい'), ('面白い', '面白い'), ('社交的', '社交的'), ('やさしい', 'やさしい'), ('積極的', '積極的'), ('甘えん坊', '甘えん坊'), ('穏やか', '穏やか'), ('寂しがり', '寂しがり'), ('社交的', '社交的')], max_length=20, null=True, verbose_name='性格'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='self_promotion',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='sexiness',
            field=models.CharField(blank=True, choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=10, null=True, verbose_name='エッチ度'),
        ),
        migrations.AddField(
            model_name='jmail',
            name='things_interesting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('恋愛', '恋愛'), ('婚活', '婚活'), ('遊び友達', '遊び友達'), ('恋人探し', '恋人探し'), ('ゲーム', 'ゲーム'), ('カフェ友達', 'カフェ友達'), ('外国人', '外国人'), ('趣味友達', '趣味友達'), ('食べ・飲み友達', '食べ・飲み友達'), ('悩み相談', '悩み相談'), ('合コン', '合コン'), ('ドライブ', 'ドライブ'), ('アニメ・漫画', 'アニメ・漫画'), ('スポーツ・フィットネス', 'スポーツ・フィットネス'), ('カラオケ', 'カラオケ'), ('ギャンブル', 'ギャンブル'), ('ショッピング', 'ショッピング'), ('ヤリモクNG', 'ヤリモクNG'), ('大人の関係', '大人の関係'), ('テレＨ・メールＨ', 'テレＨ・メールＨ'), ('ドライな関係', 'ドライな関係'), ('セフレ', 'セフレ'), ('不倫・浮気', '不倫・浮気'), ('コスプレ', 'コスプレ'), ('SM', 'SM'), ('特殊プレイ', '特殊プレイ'), ('3P・スワッピング', '3P・スワッピング'), ('写真・動画', '写真・動画')], max_length=30), blank=True, default=list, size=None, verbose_name='興味があること'),
        ),
        migrations.AlterField(
            model_name='jmail',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
